# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e4cbc3954d82dc20338fee54524fdfe00030a78a329fdc70acd19d602a55091e7b890c14a0a7a8dde90c05b767e98f0c81b61ebc394209af1baac630b17a1f9

test:
  secret_key_base: a59ee0c72ae70aa1946facceb5ddeaacd6029cbc2dffa2137b55a077a895cd5b91a4cf9816a8fee7824cc8042bc73457544a55cf59eec545fb7d4a8ff749e584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
